version: "3.8"
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --standalone --preferred-challenges http
      --agree-tos --no-eff-email --email anup.kalbalia@gmail.com
      -d icpc.rooknroll.in"
    ports:
      - "80:80"
