version: "3.8"
services:
  domserver:
    image: domjudge/domserver:8.2.3
    container_name: domserver
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: domjudge
      MYSQL_USER: domjudge_user
      MYSQL_PASSWORD: domjudge_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - submissions-data:/opt/domjudge/domserver/submissions/
      - judgings-data:/opt/domjudge/domserver/judgings/
    networks:
      - backend
      - frontend

volumes:
  submissions-data:
  judgings-data:

networks:
  backend:
    external: true
  frontend:
