services:
  domserver:
    image: domjudge/domserver:8.2.3
    container_name: domserver
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
      FPM_MAX_CHILDREN: 40

    volumes:
      - submissions-data:/opt/domjudge/domserver/submissions/
      - judgings-data:/opt/domjudge/domserver/judgings/
    networks:
      - backend
      - frontend
      - mariadb-network

volumes:
  submissions-data:
  judgings-data:

networks:
  backend:
    external: true
  frontend:
    external: true   # ✅ THIS IS IMPORTANT
  mariadb-network:
    external: true
  