version: "3.8"
services:
  db:
    image: mariadb:11.2
    container_name: mariadb
    environment:
      MYSQL_DATABASE: domjudge
      MYSQL_USER: domjudge_user
      MYSQL_PASSWORD: domjudge_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
