version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/selfsigned:/etc/nginx/certs:ro

    ports:
      - "80:80"
    networks:
      - frontend

networks:
  frontend:
    external: true
