version: "3.7"

services:
  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - db-network
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight:2.58
    container_name: redisinsight
    restart: always
    ports:
      - 5540:5540  
    networks:
      - db-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

networks:
  db-network:

volumes:
  redis-data:
